### ISSUE TITLE
Byte order

### ISSUE THREAD

**Issue by joto** [mapbox/protozero#14]
The fixed size non-varint number types float, double, fixed32, and fixed64 are stored little-endian in Protobuf. There is no special handling in `phf.hpp`, so it will only work on little-endian machines.

**Comment by joto** [comment]
As per voice discussion I will document this in the README and we'll revisit this issue if and when we need support for big-endian architectures.

**Comment by joto** [comment]
Resurrect this and put it in "Future" milestone so it doesn't get lost.

**Comment by springmeyer** [comment]
https://github.com/mapbox/protozero/commit/fca0c125c8575c9ae89332889fed66b51edef565 feels sufficient.  @joto - good to close again now?

**Comment by joto** [comment]
I think we should keep this open. If only for the benefit of the people who come to this package wondering about the state of affairs.

**Comment by joto** [comment]
I have added the code for big endian machines, but it is not tested because I don't have a big endian machine. I tried installing a virtual one using qemu but failed. Any ideas how to best test this?

I have done this now, because soon libosmium will use this code and the Debian package of libosmium should run on all platforms supported by Debian.

**Comment by sebastic** [comment]
The new libosmium Debian package failed to build on big endian architectures, see:
https://buildd.debian.org/status/package.php?p=libosmium&suite=sid

Specifically the build logs for [mips](https://buildd.debian.org/status/fetch.php?pkg=libosmium&arch=mips&ver=2.3.0-1&stamp=1440219689), [powerpc](https://buildd.debian.org/status/fetch.php?pkg=libosmium&arch=powerpc&ver=2.3.0-1&stamp=1440186338) & [s390x](https://buildd.debian.org/status/fetch.php?pkg=libosmium&arch=s390x&ver=2.3.0-1&stamp=1440189194), these are three of the big endian architectures. The build fails there with:
```
In file included from /«PKGBUILDDIR»/include/protozero/pbf_reader.hpp:29:0,
                 from /«PKGBUILDDIR»/include/protozero/pbf_message.hpp:15,
                 from /«PKGBUILDDIR»/include/osmium/io/detail/pbf_input_format.hpp:52,
                 from /«PKGBUILDDIR»/include/osmium/io/pbf_input.hpp:46,
                 from /«PKGBUILDDIR»/include/osmium/io/any_input.hpp:48,
                 from /«PKGBUILDDIR»/examples/osmium_area_test.cpp:22:
/«PKGBUILDDIR»/include/protozero/varint.hpp:20:3: error: #error "This code only works on little endian machines."
 # error "This code only works on little endian machines."
   ^
```
The build failure on [armel](https://buildd.debian.org/status/fetch.php?pkg=libosmium&arch=armel&ver=2.3.0-1&stamp=1440203091) is a long standing issue with libosmium unrelated to this big endian issue in protozero.

@joto, you can [request a guest account](https://dsa.debian.org/doc/guest-account/) on one or more of the big endian porterboxes (see [machine list](https://db.debian.org/machines.cgi)) to test the big endian changes.

**Comment by joto** [comment]
@sebastic Requesting that guest account seems to has more bureaucracy than my tax return. And it has a time limit and wouldn't be automated, so future versions can't be tested. Maybe it would be better to just package protozero into its own Debian package, then the tests would run for each new version including on all those architectures?

**Comment by sebastic** [comment]
Packaging protozero is an option, but I'm not sure if that solves this issue (I've not looked at the protozero code in depth).

How are the protozero developers expected to test the big endian changes if they also don't have access to those architectures? I expect the protozero package to need to limit its supported architectures to the little endian architectures too.

Bundled dependencies suck, so in that respect packaging protozero separately is preferred. Will protozero 1.0.0 suffice for libosmium? If not, please publish a new protozero release as soon as possible.

**Comment by sebastic** [comment]
I've packaged protozero 1.0.0 ([git repo](https://anonscm.debian.org/cgit/pkg-grass/protozero.git)), it will have to pass the [NEW queue](https://ftp-master.debian.org/new.html) first. That may take some time.

I'd like to hear the thoughts of the protozero developers how the big endian support will be handled.

**Comment by joto** [comment]
Well, I am the protozero developer. I thought I had finished the endian support, but obviously I was mistaken. I'll do that as soon as possible and release a new version.

**Comment by joto** [comment]
Okay, I had an old preprocessor check for the endianness in there. I removed this now and tagged a new release v1.1.0. This should work on architectures with little or big endian now.

**Comment by sebastic** [comment]
Thanks, I've updated protobuf package and added 4bd612677dd53d2a4752332a53db8eb87aed67a4 as patch for the libosmium package.

**Comment by joto** [comment]
This has been fixed for a while and I have just committed a (hopefully better performing) version of the byte swap functions using compiler buitins where available.
