### ISSUE TITLE
fast and safe varint impl

### ISSUE THREAD

**Issue by springmeyer** [mapbox/protozero#15]
Creating a ticket to document which varint implementation we are using and why.

Original one was from https://github.com/haberman/upb. I also experimented with an optimized one from folly, but removed it in #1 since we did not need two and I saw no distinct benefit from the folly impl.

But then @joto found a bug (I don't see a specific ticket on this) in the upb impl and switched formally to the folly impl in https://github.com/mapbox/pbf.hpp/commit/bbfddea68bc5873ba694ce6076cc9fa9f24e564f.

Tonight I ran the old version of pbf (used in mbgl) through https://scan.coverity.com which found:

![screen shot 2015-05-03 at 10 58 58 pm](https://cloud.githubusercontent.com/assets/20300/7449336/cba3f44e-f1e8-11e4-9231-cbbd1a215e19.png)

@joto - is this related perhaps to the bug you found?

Next actions:

 - [x] remove the upb license note since we are no longer using the ubp impl.
 - [x] keep this ticket open until I have a chance to run the upcoming pbf through coverity to ensure it is clean.

**Comment by joto** [comment]
@springmeyer yes, that could well be related to that bug. The bug happend when the template type T was 32bit and the values encoded were large.

I think I remember seeing an implementation of this function somewhere that wasn't templatized, but always returned a 64bit int. Not sure, though. That might be another way of fixing this problem. My focus was on first getting things work correctly, and then we could look at benchmarking and figuring out which implementation is the fastest.

**Comment by springmeyer** [comment]
@joto :+1:

**Comment by springmeyer** [comment]
coverity build pushed (https://scan.coverity.com/projects/5390). Will be available to view in 2 days, once they "okay" the project as open source.

**Comment by mourner** [comment]
What does it say?

**Comment by springmeyer** [comment]
looks like nothing major, just minor defects like potentially uninitialized variables in the tests and uncaught exceptions in tests. @joto I sent you an invite and you should now have access to the latest report (https://scan4.coverity.com/reports.htm#v13662/p11437) which is linkable via https://scan.coverity.com/projects/5390. Want to take a look through the issues and fix any you deem worthy of fixing? (obviously ignore the ones coming out of headers that are not pbf related).

**Comment by springmeyer** [comment]
none of the coverity issues of important, closing.
