### ISSUE TITLE
Explore possible SIMD speedups

### ISSUE THREAD

**Issue by danpat** [mapbox/protozero#20]
Might be worth looking at this library:

https://github.com/lemire/simdcomp

and seeing if we can apply that to varint packing (or things like `repeated uint32 geometry = 4 [ packed = true ];`).

@mourner pointed out `simdcomp` is a pretty big codebase, it would likely not be a super-smooth integration, and it would greatly increase the complexity of pbf.hpp

**Comment by springmeyer** [comment]
Yes, this could be really interesting to investigate for carmen-cache (https://github.com/mapbox/carmen-cache/blob/master/proto/index.proto) which fits this usecase: http://lemire.me/blog/archives/2014/05/19/decoding-over-4-billion-integers-per-second-in-c/

**Comment by joto** [comment]
Doesn't look like this is going to happen. Closing for now.
