### ISSUE TITLE
fuzzing

### ISSUE THREAD

**Issue by springmeyer** [mapbox/protozero#23]
There are a variety of fuzzing methods and fuzzing software out there. I'm new to this domain but started playing around with http://lcamtuf.coredump.cx/afl/ simply because is been seeing some buzz.

Docs on actual usage are minimal, but so far I've figured out that it works best by being able to pass data via stdin to a command line tool. So I added one in https://github.com/mapbox/pbf.hpp/tree/afl-fuzz. The shortcoming so far is that is only tries to parse the input as a double. We should likely extend it to try to parse multiple ways.

After installing afl and latest clang 3.6 I ran:

```
make clean
export CXX=afl-clang++
export PATH=/opt/llvm/bin/:$PATH
export AFL_HARDEN=1
export AFL_USE_ASAN=1
make ./bin/read-pbf
mkdir testcase
cp test/t/double/data-zero.pbf testcase/
afl-fuzz -i testcase/ -o findings_dir/ bin/read-pbf
```

This has not yet found any crashes. It did report `hangs` but I think they are spurious. Logging how far I got here because I'm not seeing value in pushing this much further until I have more bandwidth to experiment.

**Comment by daniel-j-h** [comment]
For reference: first example integration is done in https://github.com/mapbox/protozero/pull/48. Needs more work, though. Feel free to adapt.

**Comment by springmeyer** [comment]
https://github.com/google/libprotobuf-mutator

**Comment by joto** [comment]
I did some fuzzing using AFL and the `pbf-decoder` tool I resurrected from an old branch and spiffied up a little bit. So far no problems found.

**Comment by springmeyer** [comment]
👍  https://github.com/mapbox/protozero/blob/master/FUZZING.md looks great @joto. From my perspective I think this is closable then. You?

**Comment by joto** [comment]
I want to try the other way, too: Writing data. Not quite as easy.
