### ISSUE TITLE
make: protoc: Command not found

### ISSUE THREAD

**Issue by springmeyer** [mapbox/protozero#24]
Travis has been failing with this error since https://github.com/mapbox/protozero/commit/898f452f2fd77ae4702a352aee1b8d7191724a53

**Comment by springmeyer** [comment]
Above commit fixed for clang, but g++ builds are still hitting linking errors (https://travis-ci.org/mapbox/protozero/builds/70461042).

**Comment by springmeyer** [comment]
@joto can you replicate the above linking errors with g++ on your linux machine? Do you have any ideas to fix?

**Comment by joto** [comment]
Fixed in 909b069. Order of options on command line.
