### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by springmeyer** [mapbox/protozero#26]
With [v1.0.0 out](https://github.com/mapbox/protozero/issues/4), we should now turn our attention to performance again.

Overall I doubt we can do anything major to improve performance and I also doubt we need to. But we should still set up a few benchmarks to confirm these assumptions conclusively.

Plan:
- Write a few benchmarks that time decoding.
- We should use large vector tiles as test input.
- Let's focus to start on two different tile testcases:
  - Mapbox Streets (v6) for Yaounde: added in 81eb90b - represents varied data with strings
  - @ericfischer twitter dots for midtown NYC:  added in 453cd32  - represents long geometry arrays
- Write simplistic benchmark that times counting the number of geometries in the tile across all layers, skipping all other data.
- Compare parsing speed to using `google::protobuf::io::CodedInputStream` directly.
- Based on profiling output and how we compare to `google::protobuf::io::CodedInputStream`, then decide whether it makes sense to try to optimize.

Background:
- Early versions of protozero force inlined (https://github.com/mapbox/protozero/commit/3a370b058b43d326b783980ab6eea5c2ee16ffe3#diff-b00011152aa9901faf463b4e69c8c9acR30). This trick I learned from studying the `google::protobuf::io::CodedInputStream` code after [this comment](https://github.com/mapbox/mapnik-vector-tile/issues/1#issuecomment-22146029) by the libprotobuf and Cap'n Proto author. Any benefit to re-instating force inlining?

**Comment by springmeyer** [comment]
We need to decide on how to time the benchmarks. I think std::chrono c++ is fine. But I wanted to add that I've recently been reading posts by @lemire like http://lemire.me/blog/archives/2014/05/19/decoding-over-4-billion-integers-per-second-in-c/ and noticed some nicely minimalistic timing like https://github.com/lemire/simdcomp/blob/master/example.c#L64-L65. Also https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/blob/master/2012/06/20/testvector.cpp#L21-L58. @joto - want do you think about the best way to measure for this case? Wall clock time. CPU Time? CPU Cycles?

**Comment by joto** [comment]
There is an amazing talk by Chandler Carruth on practical benchmarking vom CppCon 2015 at https://www.youtube.com/watch?v=nXaxk27zwlk . Definitely something we can sink a lot of time into. :-)

But before we can even start, I think the first problem is: Where do we do this benchmarking? Any kind of benchmarking needs to be done on a physical machine, there are two many ways an AWS machine or other hosted solution could influence the results.

**Comment by lemire** [comment]
@joto @springmeyer 

I have a recent (haswell) PC that I use as a testing machine, for research. I would gladly grant you guys access. It is nothing special, but the machine is configured for testing purposes, and it is available on the Internet.

**Comment by joto** [comment]
We have done benchmarking in specific use cases of protozero, mainly different vector tile code. And we are using protozero in production in many cases and have seen performance is good. Unless we are seeing specific problems I don't think we need any benchmarks at this time.

**Comment by springmeyer** [comment]
👍  to close - we can revisit benchmarking again if there is a particular need that arises. Thanks again for the offer of help @lemire. 

For extra context, we've been happy doing benchmarking a bit downstream of protozero, like https://github.com/mapbox/vector-tile/blob/f4728da74f1b09384e959f081c09996bb233dc6f/bench/run.cpp, and only if protozero appears to be the bottleneck (has not yet been) would we feel inclined to return to benchmark protozero in isolation.
