### ISSUE TITLE
SIMD acceleration (performance)

### ISSUE THREAD

**Issue by lemire** [mapbox/protozero#27]
Protozero uses a reasonable vbyte decoder (https://github.com/mapbox/protozero/blob/master/include/protozero/varint.hpp).

However, for long compressible sequences of integers, it should be possible to be 2 to 3 times faster using SIMD instructions with Masked VByte:

http://maskedvbyte.org/

(A C library is freely available: https://github.com/lemire/MaskedVByte )

It would take some effort to bring it over to protozero... e.g., one needs to handle zigzag decoding. I know the code well and I could help if anyone is interested.

(Feel free to dismiss this issue. I post it just to share the information.)

**Comment by mourner** [comment]
Thanks for the suggestion! We have already started a similar discussion here: #20

**Comment by springmeyer** [comment]
@lemire - thank you for sharing https://github.com/lemire/MaskedVByte - I had not seen that effort before. Thanks!
