### ISSUE TITLE
Thinking about asserts

### ISSUE THREAD

**Issue by springmeyer** [mapbox/protozero#28]
In debug mode, we enable asserts on invalid data/non-parsable data. When not in debug mode these asserts are not fired and the likely outcome is instead a runtime exception down the line.

Both behaviors (assets and exceptions) seem useful for developers to catch bugs in their parsing code and/or invalid data.

One problem exists:

  - You write testing code that expects exceptions and uses protozero
  - You compile that code in debug mode, and asserts get enabled
  - Then the tests you wrote will likely fail if they expect exceptions

Ideas for solutions:

  - 1) Recommend users of protozero write different tests for when compiled in debug mode
  - 2) Recommend users of protozero do not compile/run their unit tests at all in debug mode
  - 3) Add a public macro to disable asserts in debug mode
  - 4) Make asserts opt-in rather than default - then they could be used either in release or debug mode.

**Comment by joto** [comment]
Ideally the asserts in the protozero code will *only* fire if there is a programming error in the protozero code or in the users code. They should not be used for corrupted input data, only for "can not happen" scenarios. In case of invalid input data, an exception should be thrown. This way the asserts help writing the code in debug mode, but they are not needed for tests outside protozero itself.

If the above is not the case in all parts of the code, I would consider this a bug.

**Comment by springmeyer** [comment]
@joto okay, can you please try building mapnik-vector-tile and see if our usage of protozero is incorrect?
