### ISSUE TITLE
New interface pbf_message and pbf_builder

### ISSUE THREAD

**Issue by joto** [mapbox/protozero#29]
I have added new interfaces in f37b1be521f1033ff24d3c39ccf8c8b3892e31f3 which augment or replace the `pbf_reader` and `pbf_writer` classes with template classes build on top of them called `pbf_message` and `pbf_builder`. I have used different names instead of changing the behaviour of the existing names to keep backwards compatibility.

The new interfaces are somewhat more type safe and allow working with symbolic names in an easy fashion. You can see an example in libosmium where I am already using this new interface. Basically the `.proto` file like
https://github.com/scrosby/OSM-binary/blob/master/src/osmformat.proto into is turned into a bunhc of `enum`s like https://github.com/osmcode/libosmium/blob/master/include/osmium/io/detail/protobuf_tags.hpp . Then you write code like https://github.com/osmcode/libosmium/blob/master/include/osmium/io/detail/pbf_decoder.hpp#L242-L266 to parse it.

Because this interface is preliminary, it is not documented or tested yet, but I use it in libosmium and I think it leads to cleaner and safer code with minimal effort.

@springmeyer @artemp any comments?

**Comment by springmeyer** [comment]
Looks very nice @joto. @artemp?

**Comment by artemp** [comment]
Anything with `template <typename T>` gets my :+1: :)  

@joto - looks good! I need to try it out to have some useful feedback though.

**Comment by joto** [comment]
I have now documented this new interface and added some tests.
