### ISSUE TITLE
Renaming the repository?

### ISSUE THREAD

**Issue by joto** [mapbox/protozero#3]
I think the name `pbf.hpp` for a repository is rather confusing. It means you'll have a directory with suffix `.hpp`. Can we find a better name?

**Comment by springmeyer** [comment]
https://github.com/mapbox/pbf is taken by js version, so... Ideas:

 - pbf-native
 - pbf-cpp
 - pbf-hpp

**Comment by springmeyer** [comment]
In reflecting more, its a little weird yes, but I actually like it. The .hpp is an explicit signal that this is a header only library that should be installed by copying it. So, I feel good about the naming and also don't have wildly better ideas. So, I'm going to close. Re-open if anyone feels strongly and has ideas for a better name.

**Comment by joto** [comment]
Reopening this because of development in #2. Because of the split into pbf reader and writer, there is no `pbf.hpp` and more. So the naming gets even more confusing. In the README there now are references to **pbf.hpp** meaning the project easily confusable with the name of a file one should include.

**Comment by mourner** [comment]
Would you prefer renaming `pbf` repo to `pbf-js`, and this one to `pbf`? That's also an option, although it would mess up remotes since redirects wouldn't work properly.

**Comment by joto** [comment]
Maybe we need a less generic name? Something that can be googled? `minpbf` for "minimal pbf" or whatever.

**Comment by joto** [comment]
In a discussion with @springmeyer we came up with "protozero". Protocol buffers with zero overhead, allocation, copy, whatever. What do people think?

We'd rename the repository and also use this as the new namespace instead of `mapbox::util`.

**Comment by mourner** [comment]
Sounds good! Can the JS implementation keep the `pbf` module? It's a very nice NPM namespace grab.

**Comment by joto** [comment]
@mourner Sure. I don't think the C++ and JS implementations have to be named the same. In fact I think it is better they are not, lest somebody think they implement exactly the same thing or based on the other one or so. That way we have the freedom of having to independent projects.

**Comment by springmeyer** [comment]
I also think its just fine to have C++ and JS be named differently.

**Comment by kkaefer** [comment]
Sounds good!

**Comment by springmeyer** [comment]
Okay, we're now `protozero` and I've:

  - done a first pass on the readme: https://github.com/mapbox/protozero/commit/e4fba01ca540c82de94352c3f87cc8e19d111391
  - updated appveyor, travis, and coveralls (they all broke)
