### ISSUE TITLE
Appveyor Windows build broken

### ISSUE THREAD

**Issue by joto** [mapbox/protozero#36]
The Windows build using gyp is broken. Two issues here:

* The first test `tests` runs only a single test case:

    All tests passed (12 assertions in 1 test case)

The output should be:

    All tests passed (4519 assertions in 86 test cases)

There are a lot of warnings `warning LNK4042: object specified more than once; extras ignored`. Could it be because all the test cases have the same file name (but they are in different directories).

* The `writer_tests` are not compiled and run at all. The google protobuf library and protoc program needs to be installed for this.

@BergWerkGIS: Could you have a look?

**Comment by joto** [comment]
Okay, this seems to be a problem with gyp: https://github.com/eristoddle/gyp/issues/238

@springmeyer any ideas?

**Comment by springmeyer** [comment]
> Could it be because all the test cases have the same file name (but they are in different directories).

Yes, this is the issue.

> Okay, this seems to be a problem with gyp: eristoddle/gyp#238

Not exactly @joto - this is something gyp blocks because older visual studio versions did not support it. There I think was a workaround (some command line option) to tell gyp to ignore this problem (then you just hope visual studio 2015 can cope).

**Comment by BergWerkGIS** [comment]
Problem was that all OBJs get created in the same directory (with the same name).

Got around it locally:
```
test cases:   86 |   66 passed | 20 failed
assertions: 4468 | 4429 passed | 39 failed
```
Still looking on how to tell gyp to do it on AppVeyor.

**Comment by BergWerkGIS** [comment]
Release builds are working and failing because of failed tests:
https://ci.appveyor.com/project/Mapbox/protozero/build/1.0.43/job/rb5b8i413qpcaofy#L715

Debug builds are failing because of some other error.
Tracking here https://github.com/mapbox/protozero/issues/37
