### ISSUE TITLE
Writer tests are not compiled and run.

### ISSUE THREAD

**Issue by joto** [mapbox/protozero#38]
There was another problem in #36 not fixed yes: The `writer_tests` are not compiled and run. This is a separate binary that needs to be compiled and run. It needs the Google Protobuf installed including the `protoc` compiler.

**Comment by BergWerkGIS** [comment]
Working on it: https://github.com/mapbox/protozero/tree/more-win-tests

**Comment by BergWerkGIS** [comment]
PR https://github.com/mapbox/protozero/pull/41
@joto ok for you to merge?

AppVeyor :white_check_mark: https://ci.appveyor.com/project/Mapbox/protozero/build/1.0.54

Are these alle tests now?
https://ci.appveyor.com/project/Mapbox/protozero/build/1.0.54/job/my1atpn1i62lc9me#L2287
```
running Debug\x86\tests.exe ...
===============================================================================
All tests passed (4519 assertions in 86 test cases)
 
running Debug\x86\writer_tests.exe ...
===============================================================================
All tests passed (63 assertions in 12 test cases)
```

**Comment by joto** [comment]
Yes, those are all the tests. Works like a char. Thanks.
