### ISSUE TITLE
Use boost for byte order checks?

### ISSUE THREAD

**Issue by joto** [mapbox/protozero#39]
Boost has some code to figure out which byte order some architecture has:
http://www.boost.org/doc/libs/1_59_0/libs/predef/doc/html/index.html

Would be better to use this than our own, but I hesitate to add a dependency. Currently we don't have any dependencies at all. I tried lifting the parts from boost that we need, but it seems rather complicated.

Opinions?

/cc @springmeyer

**Comment by springmeyer** [comment]
> but I hesitate to add a dependency. Currently we don't have any dependencies at all

Same, let's keep rolling our own.
