### ISSUE TITLE
First tag

### ISSUE THREAD

**Issue by springmeyer** [mapbox/protozero#4]
We should start versioning and tagging the code.

**Comment by springmeyer** [comment]
@joto - anything you see needing to be done before tagging a v1.0.0? Now that travis, appveyor, and coverage are all working with the latest code, I think we are ready. Great work!!

**Comment by joto** [comment]
I have done some renaming and cleanup (removed vestiges of old name etc.) and fixed documentation. Let me go through this tomorrow once more and I'll tag then.

**Comment by springmeyer** [comment]
> Let me go through this tomorrow once more and I'll tag then.
:+1:

**Comment by joto** [comment]
I tagged v1.0.0.

**Comment by springmeyer** [comment]
@joto nice work! :tada:
