### ISSUE TITLE
Optimizing varint

### ISSUE THREAD

**Issue by joto** [mapbox/protozero#46]
Decoding varints is a major bottleneck. When doing profiling, the `decode_varint` function always shows up high in the list. I have done some experiments which show that over half the varints in OSM PBF files are 1-byte varints. Optimizing this specific case speeds up reading of those files by about 10%! I optimized this by using a wrapper function around `decode_varint` that checks for this specific case and handles it locally and otherwise hands work over to the original `decode_varint` function. I believe the compiler inlines the outer function which reduces the overhead for this common case. Forcing the compiler to inline the whole function didn't do much, the function is too big to be inlined anyway.

There are some more things we need to figure out here:
- Is the OSM PBF unusual in some way that it has so many 1-byte varints? Part of this is that Protobuf uses varints for the field tags (which say which type of field something is). If the tag is <15, this will be encoded in 1 byte varint. I suspect that most Protobuf formats will do this, because this optimization is specifically mention in the Protobuf documentation. And OSM PBF uses delta encoding of IDs etc. to get small integers in several places, so this also helps. But do other formats have similar rations? We have to check how vector tiles fare here.
- Does it make sense to optimize this, or could we make some other optimization that would help in all cases. The varint decoder we use is from folly, I suspect they have done their homework on this, but we don't know their exact circumstances.
- Can we do some general optimization that just works in most cases, or do we want the programmer to give hints to the library, such as what size integer to expect or so.

I looked at the SIMD speedup things mentioned in #20 and #27, but that code is huge. Folly has some code to speed up multiple varints stored together which could help with repeated packed varints, but this will not help with the very common case of the varint-encoded tag.

**Comment by springmeyer** [comment]
See also https://github.com/google/upb/blob/master/upb/pb/varint.int.h | https://github.com/google/upb/blob/master/upb/pb/varint.c

**Comment by joto** [comment]
I have now implemented two different independent optimizations for varint. I tried them out using libosmium reading OSM files and each of the optimizations improved performance by about 5-10% using clang. The improvement is much smaller with GCC.

These changes are in `master` now:

* a54b3bbef1a7c7be8448177b740371b535fc57a2: Use new simpler skip_varint() function when iterating over packed varints instead of using decode_varint() and throwing away the result.
* ff682e2ead4bb303f8fd0db3018b1ea8536babdc: Use a wrapper function that checks the 1-byte-case described above before calling the full implementation.

Users of protozero: Please benchmark these changes in your use cases before we release a new version.

/cc @springmeyer

**Comment by springmeyer** [comment]
>  I tried them out using libosmium reading OSM files and each of the optimizations improved performance by about 5-10% using clang.

Excellent results @joto.

Which clang++ version btw? Asking because I'm still tending to use clang-3.5 for packaging binaries on linux, e.g. https://github.com/mapbox/carmen-cache/blob/master/.travis.yml#L5-L11

> Users of protozero: Please benchmark these changes in your use cases before we release a new version.

👍  I propose:

 - [ ] Carmen cache benchmark by @apendleton . I think `carmen-cache` perf should be sensitive to [decoding packed fields](https://github.com/mapbox/carmen-cache/blob/0b13ffff2d3e286b427bd202ca5b1bcc7aea88bc/proto/index.proto#L10). @apendleton you could point the `package.json` at master of protozero to test this.
 - Vector tile decoding
   - [ ] We'd need to branch and point node-mapnik's package.json as master protozero and then build some dev binaries - @mapsam - have bandwidth to do this?
   - [ ] For isolating vtile decoding speeds more acutely we could write a quick script to check how fast decoding a single large vector tile is in a loop ~ 100 times. @mapsam
   - [ ] For some real world impacts we should see if the carmen's `contextVector.js` is sensitive to this improvement: https://github.com/mapbox/carmen/pull/415#issuecomment-212986166 - @mattficke I see you've been [giving love to carmen benchmarks](https://github.com/mapbox/carmen/pull/456), want to give this a spin (coordinate with @mapsam to see when node-mapnik dev build is ready)?

**Comment by joto** [comment]
@springmeyer My numbers are with clang 3.5 and GCC 4.9.

**Comment by mapsam** [comment]
Happy to help with this!

Just pushed up a node-mapnik branch `protozero-dev` - [waiting for the binaries to build](https://travis-ci.org/mapnik/node-mapnik/builds/128387690). I'll ping back here once they are complete.

**Comment by mapsam** [comment]
@mattficke binaries are built! You should be able to point your `package.json` at the node mapnik branch with updated protozero.

```JSON
"dependencies": {
  "mapnik": "https://github.com/mapnik/node-mapnik/tarball/protozero-dev"
}
```

**Comment by springmeyer** [comment]
@apendleton @mattficke - any bandwidth on your end to help test? We'd like to make a protozero release this week, so let me know if you have any questions about what I've sketched out above.

**Comment by mattficke** [comment]
@springmeyer should be able to take a look end of today/tomorrow after I wrap up this current data loading task.

**Comment by mapsam** [comment]
> For isolating vtile decoding speeds more acutely we could write a quick script to check how fast decoding a single large vector tile is in a loop ~ 100 times

This is something I can work on today. If anyone has a specific vector tile they've tested with that would be great, otherwise I'll grab a terrain/streets tile for starters.

**Comment by springmeyer** [comment]
> otherwise I'll grab a terrain/streets tile for starters.

👍 @mapsam - something with a reasonable amount of data at z14/15 from each would be great.

**Comment by mapsam** [comment]
Some very preliminary bechmarks from a 150k tile using the node mapnik `mapnik.VectorTile.addData()` method. Here's [the script](https://gist.github.com/mapsam/071a0f66e434cfaa14ed85d276bf415b). Not seeing any major trend other than that this function scales linearly with the number of iterations.

| iterations | 3.5.13     | protzero update |
|------------|------------|-----------------|
| 20,000     | 2.23700 s  | 2.50000 s       |
| 40,000     | 4.67700 s  | 4.60300 s       |
| 60,000     | 6.81700 s  | 6.72400 s       |
| 80,000     | 8.85700 s  | 8.71000 s       |
| 100,000    | 11.14099 s | 11.28200 s      |

**Comment by joto** [comment]
The differences between 3.5.13 and protozero update go in both directions, so the benchmark is probably measuring mostly something else than the varint code. From my experience with C++/NodeJS the cost of going between C++ and Javascript and the memory managment of V8 is so great that it will likely drown out everything else. So this code is probably measuring mostly NodeJS performance and not the small optimization in the varint code. Heck, I would suspect that even calling `new Date().getTime()` costs 10 times as much time as the varint code.

Can you do this test directly from C++ without NodeJS overhead?

**Comment by mapsam** [comment]
Agreed @joto, these are just a first glance. I'll try and get a C++ bench going directly this afternoon.

**Comment by joto** [comment]
Not actionable any more.
