### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by springmeyer** [mapbox/protozero#47]
The work on a new packed API (https://github.com/mapbox/protozero/pull/45) is working well in node-mapnik/mapnik-vector-tile as as discussed with @flippmoke and @joto this should now go out in a release.

@joto - can you tag a new release at your earliest availability?

/cc @danpat (who is looking at using this new protozero in an osrm-backend develop branch)

**Comment by joto** [comment]
@springmeyer: I was waiting for a report back from @flippmoke whether the `rollback` functionality was doing the right thing for him.

**Comment by flippmoke** [comment]
@joto sorry, yes it is doing what I expect it to do!
