### ISSUE TITLE
Add command line protozero-decode tool

### ISSUE THREAD

**Issue by springmeyer** [mapbox/protozero#50]
We should add a tool that is able to decode arbitrary protobuf-encoded buffers. It would behave similarly to `protoc --decode_raw`. An example of running `protoc --decode_raw < test/t/vector_tile/data.vector.pbf` is at: https://gist.github.com/springmeyer/f7de2d636f8cd084c992af70b05805cb.

Note: reading from stdin is nice, but we could also just accept a file path.

@joto - could you work on adding this tool? I made a quick attempt at https://gist.github.com/springmeyer/6124f976b4e3c5a59561c6fbada29f3e that is probably buggy, but might offer a few steps forward.

**Comment by joto** [comment]
I looked at this, and created as decode tool based on your code. Checked in in branch `decode_tool`. Call `make tools` to compile. Reads from STDIN and writes to STDOUT.

I am not sure how to go on here. I think we have to know better, what the expected use case of this tool is.

The protobuf format doesn't have enough information in it to decode it properly without the format definition (usually in a `.proto` file). We can write code that will look at the data and try to figure out if some data looks, say, like a string or like an embedded message. But some cases are really hard to figure out (such as signed vs. unsigned integers). So this will all be trial-and-error and we'll be fiddling with the code a lot and sooner or later add command line options or so to make it configurable. But then we'll just re-invent the `.proto` format in a different way to configure this.

But how realistic is it really that we have a piece of data and no idea what the format is? Chances are, we'll have a matching `.proto` file that could tell the tool everything it needs to know to parse the protobuf message correctly using symbolic names and all.

The other thing is that such a tool is just for debugging and doesn't really have the performance requirements that protozero is developed for. So I am thinking it makes more sense to write this in a high level language, possibly using the original Google protobuf libraries. I looked around and couldn't find anything that could just read a `.proto` file and a protobuf-encoded message in one step and write it out as JSON or something. Everything I could find used `protoc` to first create some source code that could then be used to parse the message, which is a bit cumbersome. But I can't believe something like this doesn't already exist somewhere.

**Comment by springmeyer** [comment]
My desire is just a tool for debugging only that does not depend on a proto file and does not need protoc or any other dependencies. I think that is valuable on its own and I'm not worried about tweaking it occasionally as we learn more or need more. Thanks for getting this going, I'll take a look at your branch next.

**Comment by joto** [comment]
A tool `pbf-decoder` is now available. Due to the problems mentioned above it isn't that useful for normal operations, but it is there now and we can see whether it is used. It is useful at least for fuzzing.

**Comment by springmeyer** [comment]
>  It is useful at least for fuzzing.

👍
