### ISSUE TITLE
pbf_writer: } vs finish function

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/protozero#56]
At the moment, `pbf_writer` has to be carefully scoped in order to let its destructor "finish" the message writing bytes into the buffer. The artificial nesting gets even worse with multiple writers.

Although this is clever and we all love `}`, this requires nesting artificial scopes, hiding the "finish" logic in artificial scopes. Well, it's not even hiding it, since we _need_ the artificial scopes.

Can we put the destructor logic into a public `finish` (or similar) member function, the user _can_ call? 

This design would also mimic what the stdlib does eg. in [`unique_lock`](http://en.cppreference.com/w/cpp/thread/unique_lock): its destructor unlocks if it's owning the mutex but the user can still call unlock manually early on.

/cc @karenzshea

**Comment by joto** [comment]
Usually `pbf_writer` doesn't finish anything. This is only an issue when using submessages. Are you saying you want the submessage to have the `finish()` call? Can you show me some code where this is an issue?

**Comment by daniel-j-h** [comment]
Yes that's what I meant. Search the tutorial site for "scope" and you'll get some examples :)
https://github.com/mapbox/protozero/blob/master/doc/tutorial.md

**Comment by joto** [comment]
Does somebody have any examples from real code? I am a bit concerned about adding overhead to mark a `pbf_writer` as "invalid" or "already closed" and checking this on basically every call. So I want to make sure adding a `finish()` call is worth it.

**Comment by joto** [comment]
When you find yourself using extra scopes here it might make sense to factor out that code into its own functions.

After chat discussion with @daniel-j-h I am closing this here, because we couldn't find anything where a `finish()` function would gain us much. If you have a good use case, where it would help, please re-open this issue or open a new one with a code example.
