### ISSUE TITLE
Syntax Highlighting for Docs

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/protozero#61]
Example: https://github.com/mapbox/protozero/blob/master/doc/tutorial.md#an-introductory-example

At first I thought it is the cheerless Berlin autumn but then I noted it is the lack of syntax highlighting making the docs dim and grey.

Want :rainbow: 

```cpp
#include <string>
int main() {}
```

Is :cloud: 

```
#include <string>
int main() {}
```

Markdown syntax

\`\`\`cpp
int main() {}
\`\`\`

**Comment by mapsam** [comment]
The [tutorial.md docs](https://github.com/mapbox/protozero/blob/master/doc/tutorial.md#handling-embedded-messages) are SO syntax highlighted now.
