### ISSUE TITLE
1.4.3 fails to build on big endian architectures: invalid use of incomplete type

### ISSUE THREAD

**Issue by sebastic** [mapbox/protozero#66]
The protobuf 1.4.3 Debian package failed to build on [s390x](https://buildd.debian.org/status/fetch.php?pkg=protozero&arch=s390x&ver=1.4.3-1~exp1&stamp=1479225018), [hppa](https://buildd.debian.org/status/fetch.php?pkg=protozero&arch=hppa&ver=1.4.3-1%7Eexp1&stamp=1479225459), [powerpc](https://buildd.debian.org/status/fetch.php?pkg=protozero&arch=powerpc&ver=1.4.3-1~exp1&stamp=1479224804) & [ppc64](https://buildd.debian.org/status/fetch.php?pkg=protozero&arch=ppc64&ver=1.4.3-1~exp1&stamp=1479224363) (all big endian),
it looks like the endian changes are insufficient:
```
g++ -c -Iinclude -Itest/include -g -O2 -fdebug-prefix-map=/«PKGBUILDDIR»=. -fstack-protector-strong -Wformat -Werror=format-security -fvisibility-inlines-hidden -std=c++11 -Wall -Wextra -pedantic -Wsign-compare -Wsign-conversion -Wunused-parameter -Wno-float-equal -Wno-covered-switch-default -Wshadow -O0 -g -fno-inline-functions test/t/uint32/test_cases.cpp -o test/t/uint32/test_cases.o
In file included from /usr/include/c++/6/bits/move.h:57:0,
                 from /usr/include/c++/6/bits/nested_exception.h:40,
                 from /usr/include/c++/6/exception:171,
                 from /usr/include/c++/6/ios:39,
                 from /usr/include/c++/6/istream:38,
                 from /usr/include/c++/6/sstream:38,
                 from test/include/catch.hpp:70,
                 from test/include/test.hpp:6,
                 from test/t/uint32/test_cases.cpp:2:
/usr/include/c++/6/type_traits: In instantiation of 'struct std::make_unsigned<float>':
include/protozero/byteswap.hpp:56:42:   required from 'void protozero::detail::byteswap_inplace(T&) [with T = float]'
include/protozero/pbf_reader.hpp:80:33:   required from 'T protozero::pbf_reader::get_fixed() [with T = float]'
include/protozero/pbf_reader.hpp:572:33:   required from here
/usr/include/c++/6/type_traits:1831:62: error: invalid use of incomplete type 'class std::__make_unsigned_selector<float, false, false>'
     { typedef typename __make_unsigned_selector<_Tp>::__type type; };
                                                              ^~~~
/usr/include/c++/6/type_traits:1788:11: note: declaration of 'class std::__make_unsigned_selector<float, false, false>'
     class __make_unsigned_selector;
           ^~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by daniel-j-h** [comment]
This here needs to be conditional (see http://en.cppreference.com/w/cpp/types/make_unsigned) otherwise it's Undefined Behavior for types where there is no unsigned type equivalent (e.g. floats). The stdlib is nice and just fails to compile: https://github.com/mapbox/protozero/commit/a0feac5e22b8fb5f059f296f642f7c272fd1e473#diff-6c7bee11890feee852c8538f2879b852R56

> If T is an integral (except bool) or enumeration type, provides the member typedef type which is the unsigned integer type corresponding to T, with the same cv-qualifiers.

> Otherwise, the behavior is undefined. 

Was introduced in the byte swap fix for Undefined Behavior.
