### ISSUE TITLE
avoid std::string::erase() in pbf_writer::commit_submessage()

### ISSUE THREAD

**Issue by feverzsj** [mapbox/protozero#67]
The sub message building procedure for unkown length will move the sub message forward to fit the length varint in most cases.

I think, since the varint specfication doesn't forbid us to append dummy bytes to the tail, why not use 'fixed length' varint:

```c++
#include <protozero/pbf_writer.hpp>

int main()
{
    using namespace protozero;

    char buf[max_varint_length];
    memset(buf, 0x80, sizeof(buf));
    buf[sizeof(buf)-1] = 0;

    uint64_t input =  121145121;//0xfefefefe;

    auto n = write_varint(buf, input);

    if(n < sizeof(buf))
        buf[n-1] |= 0x80;

    char const* b = buf;
    auto v = decode_varint(&b, b + sizeof(buf));

    assert(v == input);
}
```

**Comment by joto** [comment]
Interesting idea. Are we sure that varints are allowed to have those extra dummy bytes? Only because our implementation can handle this doesn't mean others can. Maybe some ultra-clever SIMD-based implementation or so doesn't handle this case?

**Comment by joto** [comment]
We are just not sure that this wont break any existing libraries. Unless somebody can make a compelling argument why this can not be a problem, I don't think we can do this. Closing for now.
