### ISSUE TITLE
OAuth credentials for coveralls.io

### ISSUE THREAD

**Issue by joto** [mapbox/protozero#68]
Coveralls.io says: "Source Not Available. The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API." when trying to look at a specific file, example: https://coveralls.io/builds/9580455/source?filename=include%2Fprotozero%2Fpbf_reader.hpp .

**Comment by springmeyer** [comment]
Thanks for flagging @joto - on my list to fix.

**Comment by springmeyer** [comment]
I tried and got stuck in a loop on this page:

<img width="361" alt="screen shot 2017-01-12 at 5 01 00 pm" src="https://cloud.githubusercontent.com/assets/20300/21914522/be70d04c-d8e8-11e6-9740-a6a237ac891d.png">

**Comment by springmeyer** [comment]
Fixed by #78
