### ISSUE TITLE
Encoding of repeated fields

### ISSUE THREAD

**Issue by joto** [mapbox/protozero#69]
On https://developers.google.com/protocol-buffers/docs/encoding#packed it says:

> Note that although there's usually no reason to encode more than one key-value pair for a packed repeated field, encoders must be prepared to accept multiple key-value pairs. In this case, the payloads should be concatenated. Each pair must contain a whole number of elements.
> 
> Protocol buffer parsers must be able to parse repeated fields that were compiled as packed as if they were not packed, and vice versa. This permits adding [packed=true] to existing fields in a forward- and backward-compatible way.

This is something that protozero can not support directly. It is the job of the developer using protozero to do this correctly. Most people using protozero are probably not aware of this. I have added something in the README and I have added some functions to help with this in 60d0a19ba77e0d1ff681af5627989f2a09d9a41b. If you are using protozero you should be aware of this.

The documentation should probably be expanded to explain this in detail and show best practice.

**Comment by springmeyer** [comment]
Thanks for raising this as a documentation point. In all my uses of protozero I'm content with supporting packed fields as only packed and not supporting this back compatibility. Nevertheless its good to let developers know about this limitation of protozero.

Can you add a mention to the readme or upgrade notes about how to use `tag_and_type` if a developer wants to support both modes? (so far I see usage notes only in your commit message).
