### ISSUE TITLE
-Winteger-overflow warning

### ISSUE THREAD

**Issue by springmeyer** [mapbox/protozero#77]
Seeing this warnings with clang++-3.9 via llvm.org/apt:

```
In file included from test/t/enum/testcase.pb.cc:4:
./test/t/enum/testcase.pb.h:48:39: warning: overflow in expression; result is -2147483648 with type 'int' [-Winteger-overflow]
const int Color_ARRAYSIZE = Color_MAX + 1;
```

@joto - do you think this is worth fixing?

**Comment by joto** [comment]
I can't fix that, because that code was generated by the Google protobuf library. It is a bug in their software. This does not affect the validity of Protozero itself, because it is only used in testing that we are compatible to them.

**Comment by springmeyer** [comment]
👌
