### ISSUE TITLE
Provide a single header file amalgamation for releases

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/protozero#80]
It would be great for releases to provide a single `protozero.hpp` with all project headers merged into it. 

Why? Because it's easier for users to drop a single header into their projects. Other projects do the same e.g. see https://github.com/ThePhD/sol2/releases.

Protozero should be small enough to do this either manually or with a bit of scripting and concatenation taking care of edge cases such as header guards etc.

With https://github.com/mapbox/protozero/pull/79 in place users don't even have to adapt include paths when they include the top level header.

**Comment by joto** [comment]
See my comment on #79.
