### ISSUE TITLE
Documentation on `data_view` usage in containers

### ISSUE THREAD

**Issue by springmeyer** [mapbox/protozero#85]
Currently you can put `protozero::data_view` inside `std::vector` and compare two data_view's against each other. But if you want to put `protozero::data_view` inside a `std::map` or `std::unordered` container you'll need to provide your own `std::hash` implementation.

I think this is a good design: providing basic comparison operators, but not more. I'm creating this ticket since I don't see mention of how `data_view` work with containers in the docs. Would be good to add. @joto - I almost made a PR to do this myself, but stopped since I did not know the best place to put the doc. Could you add a short note about this where you think best?

**Comment by joto** [comment]
That is really more a general C++ or STL issue not something related to protozero.

**Comment by springmeyer** [comment]
👍
