### ISSUE TITLE
Compiling error (memory?)

### ISSUE THREAD

**Issue by mvexel** [mapbox/protozero#92]
I posted this downstream at https://github.com/osmcode/pyosmium/issues/72 but this may actually be the better location.

I run into a compiler error when compiling protozero:

```
protozero found in 'protozero-1.6.3'.
x86_64-linux-gnu-g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
error: Setup script exited with error: command 'x86_64-linux-gnu-g++' failed with exit status 4
```

My best guess is this is a memory constraint related error.. This is on a Linode 2G with (you guessed it) 2GB of RAM. Is there a way around this? I cannot easily upgrade this machine.

**Comment by geeknik** [comment]
Have you tried creating a swapfile and then try to compile after?

```
sudo fallocate -l 2G /swapfile
sudo chmod 0600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
```

**Comment by mvexel** [comment]
Thanks for the suggestion. However: 

```
Running osmium-2.14.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-72zioecy/osmium-2.14.3/egg-dist-tmp-x6f_78uu
libosmium found in 'libosmium-2.14.2'.
protozero found in 'protozero-1.6.3'.
virtual memory exhausted: Cannot allocate memory
error: Setup script exited with error: command 'x86_64-linux-gnu-g++' failed with exit status 1
```

**Comment by joto** [comment]
No, this is the wrong location. You are not compiling protozero, you are compiling pyosmium.
