### ISSUE TITLE
1.6.6 fails to build on various architectures (error: comparison of integer expressions of different signedness: 'int' and 'protozero::pbf_length_type' {aka 'unsigned int'} [-Werror=sign-compare])

### ISSUE THREAD

**Issue by sebastic** [mapbox/protozero#97]
The Debian package build for protozero 1.6.6 failed on several architectures: 

[armel](https://buildd.debian.org/status/fetch.php?pkg=protozero&arch=armel&ver=1.6.6-1&stamp=1550732138&raw=0), [armhf](https://buildd.debian.org/status/fetch.php?pkg=protozero&arch=armhf&ver=1.6.6-1&stamp=1550731972&raw=0), [i386](https://buildd.debian.org/status/fetch.php?pkg=protozero&arch=i386&ver=1.6.6-1&stamp=1550735551&raw=0), [mips](https://buildd.debian.org/status/fetch.php?pkg=protozero&arch=mips&ver=1.6.6-1&stamp=1550732120&raw=0), [mipsel](https://buildd.debian.org/status/fetch.php?pkg=protozero&arch=mipsel&ver=1.6.6-1&stamp=1550732365&raw=0), [hurd-i386](https://buildd.debian.org/status/fetch.php?pkg=protozero&arch=hurd-i386&ver=1.6.6-1&stamp=1550731785&raw=0), [kfreebsd-i386](https://buildd.debian.org/status/fetch.php?pkg=protozero&arch=kfreebsd-i386&ver=1.6.6-1&stamp=1550731995&raw=0), [powerpc](https://buildd.debian.org/status/fetch.php?pkg=protozero&arch=powerpc&ver=1.6.6-1&stamp=1550733088&raw=0), [x32](https://buildd.debian.org/status/fetch.php?pkg=protozero&arch=x32&ver=1.6.6-1&stamp=1550733252&raw=0)

```
[ 20%] Building CXX object test/CMakeFiles/reader_tests.dir/t/bool/reader_test_cases.cpp.o
cd /<<PKGBUILDDIR>>/obj-arm-linux-gnueabi/test && /usr/bin/c++   -I/<<PKGBUILDDIR>>/include -I/<<PKGBUILDDIR>>/test/include -isystem /<<PKGBUILDDIR>>/test/catch -isystem /<<PKGBUILDDIR>>/obj-arm-linux-gnueabi/test  -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -std=c++11 -Wall -Wextra -pedantic -Wsign-compare -Wunused-parameter -Wno-float-equal -Wno-covered-switch-default -Werror -o CMakeFiles/reader_tests.dir/t/bool/reader_test_cases.cpp.o -c /<<PKGBUILDDIR>>/test/t/bool/reader_test_cases.cpp
In file included from /<<PKGBUILDDIR>>/include/protozero/pbf_message.hpp:19,
                 from /<<PKGBUILDDIR>>/test/include/test.hpp:16,
                 from /<<PKGBUILDDIR>>/test/t/bool/reader_test_cases.cpp:2:
/<<PKGBUILDDIR>>/include/protozero/pbf_reader.hpp: In member function 'void protozero::pbf_reader::skip_bytes(protozero::pbf_length_type)':
/<<PKGBUILDDIR>>/include/protozero/pbf_reader.hpp:116:28: error: comparison of integer expressions of different signedness: 'int' and 'protozero::pbf_length_type' {aka 'unsigned int'} [-Werror=sign-compare]
         if (m_end - m_data < len) {
             ~~~~~~~~~~~~~~~^~~~~
At global scope:
cc1plus: error: unrecognized command line option '-Wno-covered-switch-default' [-Werror]
```

**Comment by joto** [comment]
Sorry, 32bit machines again... Fixed in 1.6.7.
